#Nome della pipeline
name: CI Pipieline

#La pipeline si avvia ad ogni push su GitHub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    #Eseguiamo su Ubuntu
    runs-on: ubuntu-latest

    steps:
      #Step 1 Scarichiamo il codice dal repository
      - name: Checkout codice
        uses: actions/checkout@v4

      #Step 2 Installiamo python
      - name: Installa python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      #Step 3 Installiamo le dipendenze
      - name: Build - installa dipendenze
        run: make build

      #Step 4 Analisi del condice con flask
      - name: Lint - analisi stile
        run: make lint

      #Step 5 Analisi sicurezza con bandit
      - name: Security - analisi sicurezza
        run: make security

      #Step 6 Eseguiamo i test con pytest e misuriamo la copertura
      - name: Test - test e copertura
        run: make test